<?xml version="1.0" encoding="UTF-8"?>
<robot generator="Robot 6.0.2 (Python 3.8.10 on linux)" generated="20230214 22:07:40.910" rpa="false" schemaversion="3">
<suite id="s1" name="Hello" source="/home/fernandamatudabaccarini/Projetos/QAcademy/RoboCamo/tests/hello.robot">
<test id="s1-t1" name="Deve exibir mensagem de boas vindas" line="5">
<kw name="Log To Console" library="BuiltIn">
<arg>Hello Robot Framework</arg>
<doc>Logs the given message to the console.</doc>
<status status="PASS" starttime="20230214 22:07:40.921" endtime="20230214 22:07:40.921"/>
</kw>
<status status="PASS" starttime="20230214 22:07:40.921" endtime="20230214 22:07:40.921"/>
</test>
<status status="PASS" starttime="20230214 22:07:40.910" endtime="20230214 22:07:40.921"/>
</suite>
<statistics>
<total>
<stat pass="1" fail="0" skip="0">All Tests</stat>
</total>
<tag>
</tag>
<suite>
<stat pass="1" fail="0" skip="0" id="s1" name="Hello">Hello</stat>
</suite>
</statistics>
<errors>
<msg timestamp="20230214 22:07:40.909" level="ERROR">Error in file '/home/fernandamatudabaccarini/Projetos/QAcademy/RoboCamo/tests/hello.robot' on line 1: Unrecognized section header '***Setings***'. Valid sections: 'Settings', 'Variables', 'Test Cases', 'Tasks', 'Keywords' and 'Comments'.</msg>
</errors>
</robot>
